### ISSUE TITLE
OpenResty?

### ISSUE THREAD

**Issue by DarkBlaez** [HSBawa/icp-ce-on-linux-containers#21] opened 2019-03-22 00:48 UTC
Many times while trying to install repeatedly everything looks like it was a success and then going to ICP you end up with this:

Welcome to OpenResty!

If you see this page, the OpenResty web platform is successfully installed and working. Further configuration is required.

For online documentation and support please refer to openresty.org.
Commercial support is available at openresty.com.

Thank you for flying OpenResty.

Thoughts? Curious as to what is truly failing. 

Thanks
DB

**Comment by HSBawa** [comment] 2019-03-22 00:58
@DarkBlaez  Seems like ICP install failed. Can you share the verbose output? 

Sometimes install fails because of lack or resources or not able to initialize certain key components.

**Comment by HSBawa** [comment] 2019-03-22 01:00
Also did it start happening recently?

**Comment by HSBawa** [comment] 2019-03-30 21:48
Not able to reproduce and no additional data received. Closing.,

**Closed by HSBawa** 2019-03-30 21:48 UTC
